In [36]:
import pandas as pd

df = pd.read_csv("atm_logs.csv")
df.head()

,atm_id,latency,packet_loss,cpu_usage,transactions_last_5min,error_code,root_cause
0,atm_7,3536,33,70,378,0,Normal
1,atm_5,1966,10,79,234,0,Normal
2,atm_9,2748,1,97,453,91,Server_Overload
3,atm_5,1605,8,60,167,0,Normal
4,atm_5,2919,26,63,216,0,Normal

In [37]:
df.groupby("root_cause").size()

root_cause
Cash_Dispenser_Fault     37
Network_Issue           144
Normal                  753
Server_Overload          66
dtype: int64

In [38]:
df.groupby("atm_id").count()

,latency,packet_loss,cpu_usage,transactions_last_5min,error_code,root_cause
atm_id,,,,,,
atm_1,94,94,94,94,94,94
atm_10,100,100,100,100,100,100
atm_2,106,106,106,106,106,106
atm_3,96,96,96,96,96,96
atm_4,105,105,105,105,105,105
atm_5,100,100,100,100,100,100
atm_6,98,98,98,98,98,98
atm_7,100,100,100,100,100,100
atm_8,97,97,97,97,97,97
atm_9,104,104,104,104,104,104

In [39]:
df.groupby("atm_id").size()

atm_id
atm_1      94
atm_10    100
atm_2     106
atm_3      96
atm_4     105
atm_5     100
atm_6      98
atm_7     100
atm_8      97
atm_9     104
dtype: int64

In [40]:
df.groupby("root_cause").size()

root_cause
Cash_Dispenser_Fault     37
Network_Issue           144
Normal                  753
Server_Overload          66
dtype: int64

In [41]:
networkdf= df[df["root_cause"]=="Network_Issue"]
networkdf.groupby("atm_id").size()

atm_id
atm_1     15
atm_10    19
atm_2     16
atm_3     14
atm_4     14
atm_5     14
atm_6     11
atm_7     13
atm_8     11
atm_9     17
dtype: int64

In [42]:
networkdf.groupby("root_cause").size()

root_cause
Network_Issue    144
dtype: int64

In [43]:
df[df['root_cause']=="Network_Issue"].groupby("atm_id").size()

atm_id
atm_1     15
atm_10    19
atm_2     16
atm_3     14
atm_4     14
atm_5     14
atm_6     11
atm_7     13
atm_8     11
atm_9     17
dtype: int64

In [44]:
df[df['root_cause']=="Network_Issue"].groupby("atm_id").size().sort_values(ascending=False)

atm_id
atm_10    19
atm_9     17
atm_2     16
atm_1     15
atm_4     14
atm_3     14
atm_5     14
atm_7     13
atm_6     11
atm_8     11
dtype: int64

In [46]:
len(df)

1000

In [47]:
len(df)

1000